name: Onbid Crawler

on:
  schedule:
    - cron: '*/1 * * * *'  # 1분마다 실행하여 설정을 확인

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Install dependencies
      run: npm install
      
    - name: Check crawler settings
      id: check-settings
      run: |
        # settings.json 파일이 있는지 확인
        if [ -f "data/settings.json" ]; then
          # 설정 파일 읽기
          SETTINGS=$(cat data/settings.json)
          IS_RUNNING=$(echo $SETTINGS | jq -r '.isRunning')
          INTERVAL=$(echo $SETTINGS | jq -r '.interval')
          LAST_CHECK=$(echo $SETTINGS | jq -r '.lastCheck')
          
          # 마지막 검색 시간으로부터 지난 시간 계산
          if [ "$LAST_CHECK" != "null" ]; then
            LAST_CHECK_TS=$(date -d "$LAST_CHECK" +%s)
            CURRENT_TS=$(date +%s)
            TIME_DIFF=$((CURRENT_TS - LAST_CHECK_TS))
            
            # 설정된 주기와 비교
            if [ "$IS_RUNNING" = "true" ] && [ $TIME_DIFF -ge $INTERVAL ]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Run crawler
      if: steps.check-settings.outputs.should_run == 'true'
      env:
        SEARCH_KEYWORD: ${{ secrets.SEARCH_KEYWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: npm run crawl 